# frozen_string_literal: true

require 'bundler/gem_tasks'
require 'rake/testtask'

Rake::TestTask.new(:test) do |t|
  t.libs << 'test'
  t.libs << 'lib'
  t.test_files = FileList['minitest/*.rb']
end

task :console do
  system 'irb -Ilib -rttytest2'
end

task default: :test
