# frozen_string_literal: true

require 'bundler/gem_tasks'
require 'rake/testtask'

Rake::TestTask.new(:test) do |t|
  t.test_files = FileList['./integration_tests_with_minitest.rb']
end

task default: :test
