name: ncsh CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    # - name: Set up C environment
    #   run: sudo apt-get update && sudo apt-get install -y build-essential
    - name: make
      run: make
    - name: make check
      run: make check
