name: ncsh CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - name: Setup GCC
      uses: Dup4/actions-setup-gcc@v1
    - name: make
      run: make
    - name: make check
      run: make check
