name: ncsh CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - name: make new test
      run: make
    - name: make debug test
      run: make debug
    - name: make check
      run: make check
    - name: make clang
      run: make -B CC=clang
    - name: make check clang
      run: make check CC=clang
